#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
语言管理器模块
"""

import os
import json


class LanguageManager:
    """语言管理器"""
    
    def __init__(self):
        """初始化语言管理器"""
        # 语言字符串
        self.languages = {
            "简体中文": {
                "app_title": "ComfyUI功能管理器",
                "system_info": "系统信息",
                "one_click_install": "一键安装",
                "smart_fix": "智能修复",
                "file_management": "文件管理",
                "one_click_start": "一键启动",
                "settings": "设置",
                "theme": "主题",
                "language": "语言",
                "logs": "日志",
                "version": "版本",
                "status_ready": "就绪",
                "status_tab_system": "当前标签: 系统信息",
                "status_tab_install": "当前标签: 一键安装",
                "status_tab_fix": "当前标签: 智能修复",
                "status_tab_file": "当前标签: 文件管理",
                "status_tab_start": "当前标签: 一键启动",
                "status_tab_settings": "当前标签: 设置",
                "confirm_close": "确认关闭",
                "confirm_close_message": "确定要关闭ComfyUI功能管理器吗？",
                "yes": "是",
                "no": "否",
                "already_running": "提示",
                "already_running_message": "ComfyUI功能管理器已经在运行中！",
                "theme_settings": "主题设置",
                "current_theme": "当前主题",
                "light_theme": "浅色主题",
                "dark_theme": "深色主题",
                "follow_system": "跟随系统",
                "theme_options": "主题选项",
                "theme_note": "说明: 主题设置将在下次启动时生效。",
                "language_settings": "语言设置",
                "current_language": "当前语言",
                "language_options": "语言选项",
                "language_note": "说明: 语言设置将在下次启动时生效。",
                "switch_to_english": "切换到English",
                "switch_to_chinese": "切换到简体中文",
                "log_settings": "日志设置",
                "current_log_level": "当前日志级别",
                "log_level_options": "日志级别选项",
                "log_note": "说明: 日志文件存储在 logs 目录中。",
                "log_operation": "操作:",
                "view_log": "查看日志",
                "version_settings": "版本信息",
                "current_version": "当前版本",
                "check_update": "检查更新",
                "check_update_note": "检查更新: 点击下方按钮检查是否有新版本",
                "about": "关于",
                "about_text": "ComfyUI功能管理器是一个用于管理ComfyUI的工具，\n提供一键安装、智能修复、文件管理和一键启动等功能。",
                "checking_update": "正在检查更新...",
                "cancel": "取消",
                "update_available": "发现新版本",
                "update_message": "当前版本: {current}\n最新版本: {latest}\n\n是否更新到最新版本？",
                "updating": "更新",
                "updating_message": "正在下载并安装更新...",
                "updating_progress": "正在更新...",
                "update_complete": "更新完成",
                "update_complete_message": "更新已完成，请重启应用程序以应用更改。",
                "no_update": "检查更新",
                "no_update_message": "当前已是最新版本！",
                "update_failed": "检查更新失败",
                "update_failed_message": "检查更新时发生错误: {error}",
                "log_viewer": "日志查看",
                "close": "关闭",
                "log_dir_not_exists": "日志目录不存在",
                "save_settings": "保存设置",
                "save_success": "保存成功",
                "save_success_message": "设置已成功保存！",
                "save_failed": "保存失败",
                "save_failed_message": "保存设置失败: {error}",
                "language_changed": "语言已更改",
                "language_changed_message": "语言已更改为简体中文。请重启应用程序以应用更改。",
                "system_detect": "系统检测",
                "hardware_info": "硬件信息",
                "storage_status": "存储状态",
                "software_info": "功能软件",
                "loading_cache": "正在加载缓存数据...",
                "click_to_detect": "点击'系统检测'按钮开始检测",
                "detecting_system": "正在检测系统信息...",
                "no_cache_data": "未找到系统检测数据，请先点击'系统检测'按钮进行检测",
                "detection_complete": "系统检测完成",
                "detection_overview": "检测概览",
                "system_overview": "系统信息",
                "cpu_info": "CPU信息",
                "gpu_info": "GPU信息",
                "memory_info": "内存信息",
                "storage_info": "存储信息",
                "network_info": "网络信息",
                "python_info": "Python信息",
                "git_info": "Git信息",
                "error_info": "错误信息",
                "hardware_detection_overview": "硬件检测概览",
                "storage_detection_overview": "存储状态检测概览",
                "software_detection_overview": "功能软件检测概览",
                "detection_time": "检测时间",
                "no_git_info": "未检测到Git信息",
                "format_error": "格式化结果失败: {error}",
                "format_hardware_error": "格式化硬件信息失败: {error}",
                "format_storage_error": "格式化存储状态信息失败: {error}",
                "format_software_error": "格式化功能软件信息失败: {error}",
                "start_detection_failed": "启动检测失败: {error}",
                "show_hardware_failed": "显示硬件信息失败: {error}",
                "show_storage_failed": "显示存储状态失败: {error}",
                "show_software_failed": "显示功能软件信息失败: {error}",
                "processing_results_failed": "处理检测结果失败: {error}",
                "processing_hardware_failed": "处理硬件检测结果失败: {error}",
                "processing_storage_failed": "处理存储状态检测结果失败: {error}",
                "processing_software_failed": "处理功能软件信息检测结果失败: {error}",
                "install_path": "安装路径",
                "browse": "浏览",
                "start_install": "开始安装",
                "create_environment": "创建环境",
                "install_pytorch": "显卡PyTorch",
                "install_comfyui": "安装ComfyUI",
                "test_start": "测试启动",
                "installation_log": "安装日志",
                "installing": "安装中...",
                "installation_complete": "安装完成",
                "installation_failed": "安装失败",
                "environment_created": "环境创建完成",
                "pytorch_installed": "PyTorch安装完成",
                "comfyui_installed": "ComfyUI安装完成",
                "comfyui_started": "ComfyUI启动成功",
                "select_install_path": "请选择安装路径",
                "path_selected": "已选择路径: {path}",
                "path_invalid": "无效路径，请重新选择",
                "installing_environment": "正在安装环境...",
                "installing_pytorch": "正在安装PyTorch...",
                "installing_comfyui": "正在安装ComfyUI...",
                "starting_comfyui": "正在启动ComfyUI...",
                "full_install_complete": "完整安装完成",
                "error_message": "错误: {message}",
                "select_path": "选择路径",
                "one_click_fix": "一键修复",
                "virtual_environment": "虚拟环境",
                "detect_pytorch": "检测PyTorch",
                "upgrade_comfyui": "升级ComfyUI",
                "update_dependencies": "更新依赖",
                "smart_fix": "智能修复",
                "fix_completed": "修复完成",
                "fix_failed": "修复失败",
                "fix_in_progress": "修复中...",
                "no_virtualenv_warning": "智能修复只能在已安装虚拟环境的路径下进行，请先在一键安装中创建虚拟环境。",
                "virtualenv_check_failed": "路径没有虚拟环境，禁止智能修复",
                "browse_path_failed": "浏览路径失败: {error}",
                "save_path_success": "保存安装路径成功: {path}",
                "save_path_failed": "保存安装路径失败",
                "update_path_failed": "更新路径失败: {error}",
                "smart_fix_start": "开始{fix_type}",
                "smart_fix_failed": "{fix_type}失败: {error}",
                "operation_completed": "操作完成",
                "operation_failed": "操作失败: {message}",
                "smart_fix_completed": "智能修复已完成，ComfyUI已恢复正常运行状态！",
                "smart_fix_failed_message": "智能修复失败: {message}\n请查看日志了解详细信息。",
                "workflows": "工作流",
                "models": "模型文件",
                "works": "个人作品",
                "filename": "文件名",
                "size": "大小",
                "modify_time": "修改时间",
                "click_start": "点击启动",
                "auto_run": "自动运行",
                "stop": "停止",
                "startup_log": "启动日志",
                "starting_comfyui": "正在启动ComfyUI...",
                "startup_complete": "启动完成",
                "startup_failed": "启动失败",
                "auto_run_enabled": "自动运行已启用",
                "auto_run_disabled": "自动运行已禁用",
                "comfyui_started": "ComfyUI启动成功",
                "comfyui_stopped": "ComfyUI已停止",
                "select_install_path": "选择安装路径",
                "warning": "提示",
                "no_comfyui_warning": "当前路径下未安装ComfyUI，文件管理功能可能无法正常使用。请先在一键安装中安装ComfyUI。",
                "save": "保存",
                "confirm_delete": "确认删除",
                "confirm_delete_message_file": "确定要删除 {filename} 吗？",
                "chinese": "简体中文",
                "english": "English",
                "debug_info": "详细调试信息",
                "info_info": "普通信息",
                "warning_info": "警告信息",
                "error_info": "错误信息",
            },
            "English": {
                "app_title": "ComfyUI Manager",
                "system_info": "System Info",
                "one_click_install": "One-click Install",
                "smart_fix": "Smart Fix",
                "file_management": "File Management",
                "one_click_start": "One-click Start",
                "settings": "Settings",
                "theme": "Theme",
                "language": "Language",
                "logs": "Logs",
                "version": "Version",
                "status_ready": "Ready",
                "status_tab_system": "Current tab: System Info",
                "status_tab_install": "Current tab: One-click Install",
                "status_tab_fix": "Current tab: Smart Fix",
                "status_tab_file": "Current tab: File Management",
                "status_tab_start": "Current tab: One-click Start",
                "status_tab_settings": "Current tab: Settings",
                "confirm_close": "Confirm Close",
                "confirm_close_message": "Are you sure you want to close ComfyUI Manager?",
                "yes": "Yes",
                "no": "No",
                "already_running": "Warning",
                "already_running_message": "ComfyUI Manager is already running!",
                "theme_settings": "Theme Settings",
                "current_theme": "Current theme",
                "light_theme": "Light theme",
                "dark_theme": "Dark theme",
                "follow_system": "Follow system",
                "theme_options": "Theme options",
                "theme_note": "Note: Theme settings will take effect on next startup.",
                "language_settings": "Language Settings",
                "current_language": "Current language",
                "language_options": "Language options",
                "language_note": "Note: Language settings will take effect on next startup.",
                "switch_to_english": "Switch to English",
                "switch_to_chinese": "Switch to Chinese",
                "log_settings": "Log Settings",
                "current_log_level": "Current log level",
                "log_level_options": "Log level options",
                "log_note": "Note: Log files are stored in the logs directory.",
                "log_operation": "Operation:",
                "view_log": "View Logs",
                "version_settings": "Version Info",
                "current_version": "Current version",
                "check_update": "Check Update",
                "check_update_note": "Check Update: Click the button below to check for new versions",
                "about": "About",
                "about_text": "ComfyUI Manager is a tool for managing ComfyUI,\nproviding one-click installation, smart fix, file management, and one-click start functions.",
                "checking_update": "Checking for updates...",
                "cancel": "Cancel",
                "update_available": "New Version Found",
                "update_message": "Current version: {current}\nLatest version: {latest}\n\nDo you want to update to the latest version?",
                "updating": "Updating",
                "updating_message": "Downloading and installing update...",
                "updating_progress": "Updating...",
                "update_complete": "Update Complete",
                "update_complete_message": "Update has been completed. Please restart the application to apply changes.",
                "no_update": "Check Update",
                "no_update_message": "You are already using the latest version!",
                "update_failed": "Update Check Failed",
                "update_failed_message": "An error occurred while checking for updates: {error}",
                "log_viewer": "Log Viewer",
                "close": "Close",
                "log_dir_not_exists": "Log directory does not exist",
                "save_settings": "Save Settings",
                "save_success": "Save Success",
                "save_success_message": "Settings have been saved successfully!",
                "save_failed": "Save Failed",
                "save_failed_message": "Failed to save settings: {error}",
                "language_changed": "Language Changed",
                "language_changed_message": "Language has been changed to English. Please restart the application for the changes to take effect.",
                "system_detect": "System Detection",
                "hardware_info": "Hardware Info",
                "storage_status": "Storage Status",
                "software_info": "Software Info",
                "loading_cache": "Loading cached data...",
                "click_to_detect": "Click 'System Detection' to start detection",
                "detecting_system": "Detecting system information...",
                "no_cache_data": "No system detection data found, please click 'System Detection' first",
                "detection_complete": "System detection completed",
                "detection_overview": "Detection Overview",
                "system_overview": "System Overview",
                "cpu_info": "CPU Info",
                "gpu_info": "GPU Info",
                "memory_info": "Memory Info",
                "storage_info": "Storage Info",
                "network_info": "Network Info",
                "python_info": "Python Info",
                "git_info": "Git Info",
                "error_info": "Error Info",
                "hardware_detection_overview": "Hardware Detection Overview",
                "storage_detection_overview": "Storage Detection Overview",
                "software_detection_overview": "Software Detection Overview",
                "detection_time": "Detection Time",
                "no_git_info": "No Git information detected",
                "format_error": "Formatting result failed: {error}",
                "format_hardware_error": "Formatting hardware info failed: {error}",
                "format_storage_error": "Formatting storage status failed: {error}",
                "format_software_error": "Formatting software info failed: {error}",
                "start_detection_failed": "Failed to start detection: {error}",
                "show_hardware_failed": "Failed to show hardware info: {error}",
                "show_storage_failed": "Failed to show storage status: {error}",
                "show_software_failed": "Failed to show software info: {error}",
                "processing_results_failed": "Failed to process detection results: {error}",
                "processing_hardware_failed": "Failed to process hardware detection results: {error}",
                "processing_storage_failed": "Failed to process storage status results: {error}",
                "processing_software_failed": "Failed to process software info results: {error}",
                "install_path": "Install Path",
                "browse": "Browse",
                "start_install": "Start Installation",
                "create_environment": "Create Environment",
                "install_pytorch": "Install PyTorch",
                "install_comfyui": "Install ComfyUI",
                "test_start": "Test Start",
                "installation_log": "Installation Log",
                "installing": "Installing...",
                "installation_complete": "Installation Complete",
                "installation_failed": "Installation Failed",
                "environment_created": "Environment Created",
                "pytorch_installed": "PyTorch Installed",
                "comfyui_installed": "ComfyUI Installed",
                "comfyui_started": "ComfyUI Started",
                "select_install_path": "Please select installation path",
                "path_selected": "Path selected: {path}",
                "path_invalid": "Invalid path, please select again",
                "installing_environment": "Installing environment...",
                "installing_pytorch": "Installing PyTorch...",
                "installing_comfyui": "Installing ComfyUI...",
                "starting_comfyui": "Starting ComfyUI...",
                "full_install_complete": "Full installation completed",
                "error_message": "Error: {message}",
                "select_path": "Select Path",
                "one_click_fix": "One-click Fix",
                "virtual_environment": "Virtual Environment",
                "detect_pytorch": "Detect PyTorch",
                "upgrade_comfyui": "Upgrade ComfyUI",
                "update_dependencies": "Update Dependencies",
                "smart_fix": "Smart Fix",
                "fix_completed": "Fix Completed",
                "fix_failed": "Fix Failed",
                "fix_in_progress": "Fixing...",
                "no_virtualenv_warning": "Smart fix can only be performed in paths with virtual environment installed. Please create a virtual environment in One-click Install first.",
                "virtualenv_check_failed": "No virtual environment in path, smart fix disabled",
                "browse_path_failed": "Browse path failed: {error}",
                "save_path_success": "Save installation path successful: {path}",
                "save_path_failed": "Save installation path failed",
                "update_path_failed": "Update path failed: {error}",
                "smart_fix_start": "Start {fix_type}",
                "smart_fix_failed": "{fix_type} failed: {error}",
                "operation_completed": "Operation completed",
                "operation_failed": "Operation failed: {message}",
                "smart_fix_completed": "Smart fix completed, ComfyUI has been restored to normal operation!",
                "smart_fix_failed_message": "Smart fix failed: {message}\nPlease check the log for details.",
                "workflows": "Workflows",
                "models": "Models",
                "works": "Works",
                "filename": "File Name",
                "size": "Size",
                "modify_time": "Modify Time",
                "click_start": "Click Start",
                "auto_run": "Auto Run",
                "stop": "Stop",
                "startup_log": "Startup Log",
                "starting_comfyui": "Starting ComfyUI...",
                "startup_complete": "Startup Complete",
                "startup_failed": "Startup Failed",
                "auto_run_enabled": "Auto Run Enabled",
                "auto_run_disabled": "Auto Run Disabled",
                "comfyui_started": "ComfyUI Started",
                "comfyui_stopped": "ComfyUI Stopped",
                "select_install_path": "Select Install Path",
                "warning": "Warning",
                "no_comfyui_warning": "ComfyUI is not installed in the current path. File management functions may not work properly. Please install ComfyUI first in One-click Install.",
                "save": "Save",
                "confirm_delete": "Confirm Delete",
                "confirm_delete_message_file": "Are you sure you want to delete {filename}?",
                "chinese": "Chinese",
                "english": "English",
                "debug_info": "Detailed debug information",
                "info_info": "General information",
                "warning_info": "Warning information",
                "error_info": "Error information",
            }
        }
        
        # 获取当前语言设置
        self.current_language = self._get_current_language()
    
    def _get_current_language(self):
        """获取当前语言设置"""
        config_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "config.json")
        try:
            print(f"读取配置文件: {config_path}")
            if os.path.exists(config_path):
                print(f"配置文件存在")
                with open(config_path, "r", encoding="utf-8") as f:
                    config = json.load(f)
                    print(f"配置内容: {config}")
                    language = config.get("language", "简体中文")
                    print(f"读取到的语言设置: {language}")
                    return language
            print(f"配置文件不存在")
            return "简体中文"
        except Exception as e:
            print(f"获取语言设置失败: {e}")
            from comfyui_manager.utils.logger import Logger
            Logger().error(f"获取语言设置失败: {e}")
            return "简体中文"
    
    def get(self, key):
        """获取语言字符串"""
        try:
            return self.languages[self.current_language].get(key, key)
        except Exception as e:
            return key
    
    def get_language(self):
        """获取当前语言"""
        return self.current_language
    
    def refresh_language(self):
        """刷新语言设置"""
        self.current_language = self._get_current_language()
        print(f"语言设置已刷新，当前语言: {self.current_language}")


# 全局语言管理器
print("初始化语言管理器...")
lang_manager = LanguageManager()
print(f"语言管理器初始化完成，当前语言: {lang_manager.get_language()}")
